### ISSUE TITLE
FileNotFoundError when loading

### ISSUE THREAD

**Issue by andhamel** [stefanpeidli/mousipy#1]
Hi all, 

After installing `mousipy` with `pip`, I ran the recommended code and received this error:

```
import scvelo as scv
from mousipy import translate

FileNotFoundError: [Errno 2] No such file or directory: 'src/mousipy/biomart/human_to_mouse_biomart_export.csv'
```

Do I need to download this csv?

**Comment by stefanpeidli** [comment]
Hi,

Thanks for posting the first issue!

I found and fixed the bug, try to reinstall using
`pip install mousipy --upgrade`
and try running your code then one more time. You do not need to download any csv.

Best,
Stefan

**Comment by andhamel** [comment]
Thank you! That worked.

I used the translate function, and I don't think it worked. If I am converting from mouse to human, do the mouse genes need to be in the gene symbol format, e.g. Ras, or can they be in ensembl format? The genes in my anndata.var are ensembl ENSMUSG IDs.

**Comment by stefanpeidli** [comment]
Great!

At the moment this function can only translate gene symbols to gene symbols. I can make it also accept ensemble IDs, but that might take me a while (I'm currently abroad). Faster solution for you is to map your ensemble IDs to gene symbols like this:
```
import mygene
mg = mygene.MyGeneInfo()
query = mg.querymany(['ENSMUSG00000037761', 'ENSMUSG00000037754', 'ENSMUSG00000074625', 'ENSMUSG00000093120'], scopes='ensembl.gene', fields=['symbol'], species="mouse")
conversion_dict = {x['query']: x['symbol'] for x in query if 'query' in x.keys()}
conversion_dict

> querying 1-4...done.
> Finished.
> {'ENSMUSG00000037761': 'Actr5',
>  'ENSMUSG00000037754': 'Ppp1r16b',
>  'ENSMUSG00000074625': 'Arhgap40',
>  'ENSMUSG00000093120': 'Mir3474'}
```

**Comment by andhamel** [comment]
Thank you! My only concern with this solution at the moment is if a ENSMUSG id maps to more than one gene symbol, which would result in a non-unique index.

**Comment by stefanpeidli** [comment]
Good point. I think really the best thing would be if I implement a way to map ensemble IDs between mouse and human directly. I will keep you posted on the progress!

**Comment by stefanpeidli** [comment]
Hi,

mousipy can now translate to and from Ensembl IDs. Also it can translate from mouse to human now.
Simply upgrade using:
`pip install -U mousipy`

Best,
Stefan
