### ISSUE TITLE
from human to mouse

### ISSUE THREAD

**Issue by sandrav-CGEN** [stefanpeidli/mousipy#3]
Hi!
Are you planning to add a function that can translate from human genes to mouse genes?
Best, Sandra

**Comment by stefanpeidli** [comment]
Hi Sandra,
Sorry for my late reply, pre-Christmas time is crazy busy. I will add it to my to do list and will try to work on it during the holidays. Should be easily implemented.
Best,
Stefan

**Comment by stefanpeidli** [comment]
Finally, mousipy can now translate from human to mouse as well. Also it can translate to and from Ensemble IDs now.
Simply upgrade using:
`pip install -U mousipy`

Best,
Stefan
