### ISSUE TITLE
 FileNotFoundError: human_to_mouse.csv

### ISSUE THREAD

**Issue by georginaalbadri** [stefanpeidli/mousipy#5]
Hi, I used pip install mousipy to install and have tried to use translate on an anndata object that has mouse gene symbols. I'm getting a FileNotFoundError:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/...python3.11/site-packages/mousipy/./hcop/human_to_mouse.csv'

**Comment by stefanpeidli** [comment]
Hi, the recent version seemed to contain a bug. I will try to fix it soon. For now you can use an old version instead using:
`pip install -U mousipy==0.1.3`

**Comment by stefanpeidli** [comment]
Fixed with v0.1.5. Simply upgrade using `pip install -U mousipy`
